### ISSUE TITLE
Uhh i need some help i never using cargo

### ISSUE THREAD

**Issue by GroundNF** [zKevz/PixelWorldProxy#1]
![Screenshot_20220101-184233](https://user-images.githubusercontent.com/96753557/147849736-11f20044-462d-4c8a-95bd-8a4205389e24.png)

**Comment by zKevz** [comment]
install it

**Comment by qaxl** [comment]
you need to have atleast rustc 1.56

**Comment by qaxl** [comment]
consider reading this: https://www.rust-lang.org/learn/get-started

**Comment by GroundNF** [comment]
> you need to have atleast rustc 1.56

Did u know how to install it?

**Comment by qaxl** [comment]
Look into the link I sent, use the rust up installer instead of your systems package manager.
